export const LOAD_MEDIA = "LOAD_MEDIA"
export const CURRENT_INDEX_INCREMENT = "CURRENT_INDEX_INCREMENT"
export const CURRENT_INDEX_DECREMENT = "CURRENT_INDEX_DECREMENT"
export const CURRENT_INDEX_SET = "CURRENT_INDEX_SET"
